#!/bin/sh
#
# Start keyboard map
#

start() {
	printf "Starting keymap"
	loadkmap < /etc/nokia-n900.kmap
	echo "OK"
}

stop() {
	printf "Stopping keymap"
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
